title: Pacman Treasure Hunt of the Pi Terminal
hero_image: images/banner.png
description: ....
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, programming-0,
interests: "games, hacking"
technologies: "terminal, command line"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Your mission
